### PR TITLE
Pats edits

### PR DESCRIPTION
**Pull request by pschloss**
I've edited the Rmd file. A couple of things to note...

* The advanced adenoma treatment model doesn't do well, it's no different from random
* I simplified the modeling section by reorganizing the text and removing text that was already in a table or should be in a table. The mtry parameter values should go into a supplemental table rather than in the text

### CODE REVIEW

**Comment by pschloss** [comment]
I edited the sentence that Reviewer 1 questioned. Also, can you put the Microbiome-version of the abstract back in place of the revised one?

**Comment by pschloss** [comment]
I replaced the abstract - make sure that the numbers work out with the revised method

**Comment by marcsze** [comment]
@pschloss do you want me to make a table?

**Comment by pschloss** [comment]
yes!

**Pull request merged**
